language: php

matrix:
 include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=1 DEPLOY_AFTER=true
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1
 allow_failures:
  - php: hhvm
    env: WP_VERSION=latest WP_MULTISITE=1

before_script:
 - composer install
 - bash setup-testenv.sh wordpress_test root '' localhost $WP_VERSION
 - npm install -g grunt-cli
 - npm install
 - grunt build

script: phpunit

after_success:
 - grunt dist
 - if [ ${DEPLOY_AFTER} = true ]; then ls dist; fi
