language: php

cache:
 - composer
 - npm

php:
  - 5.4
  - 5.5
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=1 WP_VERSION_CURRENT=4.0
  - WP_VERSION=4.0 WP_MULTISITE=1 WP_VERSION_CURRENT=4.0

matrix:
 fast_finish: true
 allow_failures:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1 DEPLOY_AFTER=false

install:
 - composer install
 - npm install -g grunt-cli
 - npm install
 - grunt build

before_script:
 - bash setup-testenv.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

after_success:
 - if [ ${TRAVIS_PHP_VERSION} = "5.3" ] && [ ${WP_VERSION} = ${WP_VERSION_CURRENT} ]; then  grunt dist; fi
 - if [ ${TRAVIS_PHP_VERSION} = "5.3" ] && [ ${WP_VERSION} = ${WP_VERSION_CURRENT} ]; then curl --ftp-create-dirs -T dist/muneco.zip -u $FTP_U:$FTP_P ftp://$FTP_D/muneco.zip; fi
