language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
 - WP_VERSION=latest WP_MULTISITE=1
 - WP_VERSION=4.0 WP_MULTISITE=1

matrix:
 include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1
 allow_failures:
  - php: hhvm
    env: WP_VERSION=latest WP_MULTISITE=1

before_script:
 - composer install
 - bash setup-testenv.sh wordpress_test root '' localhost $WP_VERSION
 - npm install -g grunt-cli
 - npm install
 - grunt build

script: phpunit

after_success:
 - grunt dist
 - "curl --ftp-create-dirs -T dist/muneco.zip -u $FTP_U:$FTP_P ftp://$FTP_Dmuneco.zip"

